kind: Deployment
apiVersion: apps/v1
metadata:
  name: reviews
spec:
  selector:
    matchLabels:
      app: reviews
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - name: reviews
          image: chthota/reviews:latest